Rails.application.routes.draw do
  root 'articles#index'
  get '/register', to: 'users#new'
  get '/profile/:username', to: 'users#show', as: 'profile'
  post '/register', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/article/:slug', to: 'articles#show', as: 'article'
  get '/editor', to: 'articles#new'
  post '/article', to: 'articles#create', as: 'create_article'
  get '/editor/:slug', to: 'articles#edit', as: 'edit_article'
  patch '/article/:slug', to: 'articles#update'
  delete '/article/:slug', to: 'articles#destroy', as: 'destroy_article'
end
